### ISSUE TITLE
Plasma not starting

### ISSUE THREAD

**Issue by matlink** [plasma-phone-packaging/pm-flashtool#3]
I've successfully installed PM over CM 13 (Lollipop) using the Multirom way.
However, once restarted the phone was still under raw CM android, not Plasma.
I tried using the shell to start the lxc container. First of all the `/data/lxc/lxc/bin` was not in the `PATH` bash variable, neither was `/data/lxc/lxc/lib` in `LD_LIBRARY_PATH`. Even with that fixed, lxc-start cannot be executed:
`error: only position independent executables (PIE) are supported.`

Has PM been tested under CM 13?

**Comment by bhush9** [comment]
Hello, sorry if documentation was not bit clear on this but, you need to install custom and stripped down version of CM, which is available at : neon.plasma-mobile.org/cm-stripped.zip

See instructions at https://community.kde.org/Plasma/Mobile/CyanogenModBase#MultiROM_instructions_.28For_dualboot.29

Thanks

**Comment by matlink** [comment]
Thank you for you quick answer. I'll try this as soon as I can.
