### ISSUE TITLE
acbf.info 404 error trying to install on nexus 5x

### ISSUE THREAD

**Issue by NebulaBC** [plasma-phone-packaging/pm-flashtool#48]
I keep getting this error
I have tried to install multiple branches, and nothing will work, and have clicked the link in my browser and it looks like its down (I found a thread from quite a while ago saying its down, so I don't think its going back up soon)
I was wondering if anyone had any temporary workarounds I could use to get Plasma Mobile on my 5x.

Cloning into 'fetch-demo-data'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 15 (delta 1), reused 15 (delta 1), pack-reused 0
Unpacking objects: 100% (15/15), 1.60 KiB | 234.00 KiB/s, done.
--2020-09-16 20:05:44--  http://acbf.info/download?id=0016
Resolving acbf.info (acbf.info)... 5.10.124.141
Connecting to acbf.info (acbf.info)|5.10.124.141|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-09-16 20:05:45 ERROR 404: Not Found.

**Comment by omegajimes** [comment]
It looks like Plasma Mobile is broken on the Nexus 5X for the time being.  It would have been nice to have some warning on the website before reaching this point.

**Comment by hmlendea** [comment]
Still broken apparently

**Comment by NebulaBC** [comment]
This was a while ago, and if I remember right I did find a fix. It really sucks that more progress has not been made on plasma mobile in the past while and things were broke with no notice.

**Comment by hmlendea** [comment]
Yeah, well, I did manage to install it in the end. And then found out that `bullhead` is not supported anymore and I can't do anything with it. But it did boot.
A shame it's abandoned, really. :(

**Comment by NebulaBC** [comment]
It really does suck that it is abandoned, I bought a 5x thinking that I would be able to install linux on it in the future once it was more stable so I could daily drive it. Now my Nexus 5x is useless and I am going to have to get a pinephone if I want to use linux...

**Comment by NebulaBC** [comment]
The project is defunct + Issue is old. Closing.
