### ISSUE TITLE
plasma-rootfs not found

### ISSUE THREAD

**Issue by jcuenod** [plasma-phone-packaging/pm-flashtool#5]
line 23 in `flash-multirom` has:

    wget -c http://neon.plasma-mobile.org/rootfs/plasma-rootfs-`cat rootfs_stamp`.tar.gz

the `plasma-rootfs` prefix was wrong for me though; the last three rootfs files I see are `pm-rootfs...`

**Comment by rajpratik71** [comment]
Manually change the line to wget -c http://image.plasma-mobile.org/rootfs/pm-rootfs-`cat rootfs_stamp`.tar.gz

**Comment by rajpratik71** [comment]
Sorry this on wget -c http://images.plasma-mobile.org/rootfs/pm-rootfs-`cat rootfs_stamp`.tar.gz

**Comment by jbruechert** [comment]
the mutirom script is currently not supported and it's likely that it won't work at all. Please just make a backup of your current ROM and use the normal flash script.

**Comment by bhush9** [comment]
Ass @JBBgameich mentioned, this method of flashing with multirom is outdated. I'll remove script from repo to not cause further confusion
